__default__:
  account: iazevedo
  partition: serc
  email: ktehranchi@stanford.edu
  walltime: 00:30:00   # time limit for each job
  chdir: $GROUP_HOME/kamran/pypsa-usa/workflow
  output: logs/slurm/{rule}-%j.out
  error: logs/slurm/err_{rule}-%j.err
  extra: |
    ml python/3.9.0
    ml gurobi/10.0.1_py39

build_renewable_profiles:
  walltime: 02:00:00

solve_network:
  walltime: 06:00:00
